apiVersion: v2
name: confluence
description: A chart for installing Confluence Data Center on Kubernetes
type: application
version: 1.17.0
appVersion: 8.5.4
kubeVersion: ">=1.21.x-0"
keywords:
- Confluence
- Confluence Server
- Confluence Data Center
- Confluence DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/confluence.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |-
    - "Make test pod metadata and spec configurable (#727)"
    - "Update default Confluence version (#729)"
    - "Optional analytics/support ConfigMap (#721)"
    - "Fix ingress annotations comment (#720)"
    - "Apply securityContext only if it is explicitly enabled (#717)"

dependencies:
- name: common
  version: 1.2.5
  repository: https://atlassian.github.io/data-center-helm-charts
