apiVersion: v2
name: confluence
description: A chart for installing Confluence Data Center on Kubernetes
type: application
version: 1.14.0
appVersion: 7.19.11
kubeVersion: ">=1.21.x-0"
keywords:
- Confluence
- Confluence Server
- Confluence Data Center
- Confluence DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/confluence.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |-
    - "Add liveness probes, make readinessProbes configurable (#626)"
    - "Support running Jira and Confluence containers as non root (incl running in OpenShift) (#623)"
    - "make sharedHome.permissionFix.command helper to be per-product (#622)"
    - "Unset default limits for Confluence (#616)"
    - "Synchrony missing container limits (#615)"

dependencies:
- name: common
  version: 1.2.3
  repository: https://atlassian.github.io/data-center-helm-charts
