apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: 1.14.0
appVersion: 5.1.3
kubeVersion: ">=1.21.x-0"
keywords:
- Crowd
- Crowd Server
- Crowd Data Center
- Crowd DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Add liveness probes, make readinessProbes configurable (#626)"
    - "make sharedHome.permissionFix.command helper to be per-product (#622)"

dependencies:
- name: common
  version: 1.2.3
  repository: https://atlassian.github.io/data-center-helm-charts
