apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 1.17.0
appVersion: 9.12.0
kubeVersion: ">=1.21.x-0"
keywords:
- Jira
- Jira Software
- Jira Server
- Jira Data Center
- Jira DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Make test pod metadata and spec configurable (#727)"
    - "Optional analytics/support ConfigMap (#721)"
    - "Fix ingress annotations comment (#720)"

dependencies:
- name: common
  version: 1.2.5
  repository: https://atlassian.github.io/data-center-helm-charts
